---
exclude_patterns:
  - "**/__tests__/**"
  - "**/__mocks__/**"
  - "**/node_modules/**"
  - "**/dist/**"
  - "**/coverage/**"

checks:
  eslint:
    enabled: true
    config:
      ignore_warnings:
        - "no-unused-expressions"

  pattern_search:
    - pattern: "http://"
      comment: "Unencrypted request over HTTP detected"
      severity: "info"