"""Add Inquiry History model

Revision ID: 0fef0d2b5a2a
Revises: f013bcca5e90
Create Date: 2025-02-07 20:34:02.402919

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "0fef0d2b5a2a"
down_revision = "f013bcca5e90"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "inquiryhistory",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("inquiry_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("new_data", sa.JSON(), nullable=True),
        sa.Column(
            "action",
            sa.Enum("CREATE", "UPDATE", "DELETE", name="actiontype"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["inquiry_id"], ["inquiry.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column(
        "response", sa.Column("inquiry_history_id", sa.Integer(), nullable=False)
    )
    op.create_foreign_key(
        None, "response", "inquiryhistory", ["inquiry_history_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "response", type_="foreignkey")
    op.drop_column("response", "inquiry_history_id")
    op.drop_table("inquiryhistory")
    # ### end Alembic commands ###
