name: Create AWS Core Infra

on:
  workflow_dispatch:

env:
  AWS_REGION: us-west-2


jobs:
  aws-core-infra:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@0e613a0980cbf65ed5b322eb7a1e075d28913a83
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}


      - name: Setup Terraform
        uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd
        with:
          terraform_version: 1.10.1 

      - name: Change to Terraform directory
        run: cd ./infra

      - name: Initialize Terraform
        working-directory: ./infra
        run: terraform init

      - name: Validate Terraform configuration
        working-directory: ./infra
        run: terraform validate

      - name: Taint ECS Backend and Frontend Services
        working-directory: ./infra
        run: |
          terraform validate
          # terraform taint module.ecs-backend.aws_ecs_service.this
          # terraform taint module.ecs-backend.aws_ecs_task_definition.this
          # terraform taint module.ecs-frontend.aws_ecs_service.this
          # terraform taint  module.ecs-frontend.aws_ecs_task_definition.this


      - name: Apply Terraform configuration
        working-directory: ./infra
        env:
          TF_VAR_aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          TF_VAR_aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: terraform apply -auto-approve
