name: Test

on: [push]

jobs:

  test:
    runs-on: ubuntu-latest

    env:
      POSTGRES_SERVER: localhost
      POSTGRES_PORT: 5432
      POSTGRES_DB: app
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: changethis
      SENTRY_DSN: 1234
      # This would be set to the production domain with an env var on deployment
      DOMAIN: localhost
      
      # Environment: local, staging, production
      ENVIRONMENT: local
      
      PROJECT_NAME: "Full Stack FastAPI Project"
      STACK_NAME: full-stack-fastapi-project
      
      # Backend
      BACKEND_CORS_ORIGINS: "http://localhost,http://localhost:5173,https://localhost,https://localhost:5173,http://localhost.tiangolo.com"
      SECRET_KEY: changethis
      FIRST_SUPERUSER: admin@example.com
      FIRST_SUPERUSER_PASSWORD: changethis
      
      # Emails
#      SMTP_HOST:
#      SMTP_USER:
#      SMTP_PASSWORD:
      EMAILS_FROM_EMAIL: info@example.com
      SMTP_TLS: True
      SMTP_SSL: False
      SMTP_PORT: 587

      # Configure these with your own Docker registry images
      DOCKER_IMAGE_FRONTEND: survey_frontend
      DOCKER_IMAGE_BACKEND: survey_backend
      
      # Other config variables
      DOCKER_IMAGE_CELERYWORKER: survey_celeryworker
      TAG: latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Copy env
        run: cp .env.example .env

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

#      - run: docker compose build
#      - run: docker compose down -v --remove-orphans
      - run: docker compose up -d

      - name: Lint
        run: docker compose exec backend bash /app/scripts/lint.sh

      - name: Run tests
        run: docker compose exec backend bash /app/tests-start.sh "Coverage for ${{ github.sha }}"
      - run: docker compose down -v --remove-orphans

      - name: Store coverage files
        uses: actions/upload-artifact@v4
        with:
          name: coverage-html
          path: backend/htmlcov
          include-hidden-files: true